#################################################################
# Makefile generated by Xilinx Platform Studio 
# Project:/home/eisele/src/hw/microblaze/xps/enc_mp/test_mp_sys.xmp
#
# WARNING : This file will be re-generated every time a command
# to run a make target is invoked. So, any changes made to this  
# file manually, will be lost when make is invoked next. 
#################################################################

XILINX_EDK_DIR = /opt/Xilinx/14.7/ISE_DS/EDK

SYSTEM = test_mp_sys

MHSFILE = test_mp_sys.mhs

FPGA_ARCH = spartan6

DEVICE = xc6slx45tcsg324-3

INTSTYLE = default

XPS_HDL_LANG = vhdl
GLOBAL_SEARCHPATHOPT = 
PROJECT_SEARCHPATHOPT = 

SEARCHPATHOPT = $(PROJECT_SEARCHPATHOPT) $(GLOBAL_SEARCHPATHOPT)

SUBMODULE_OPT = 

PLATGEN_OPTIONS = -p $(DEVICE) -lang $(XPS_HDL_LANG) -intstyle $(INTSTYLE) $(SEARCHPATHOPT) $(SUBMODULE_OPT) -msg __xps/ise/xmsgprops.lst

OBSERVE_PAR_OPTIONS = -error yes

MICROBLAZE_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/microblaze/mb_bootloop.elf
MICROBLAZE_BOOTLOOP_LE = $(XILINX_EDK_DIR)/sw/lib/microblaze/mb_bootloop_le.elf
PPC405_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc405/ppc_bootloop.elf
PPC440_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc440/ppc440_bootloop.elf
BOOTLOOP_DIR = bootloops

MICROBLAZE_1_BOOTLOOP = $(BOOTLOOP_DIR)/microblaze_1.elf

MICROBLAZE_0_BOOTLOOP = $(BOOTLOOP_DIR)/microblaze_0.elf

BRAMINIT_ELF_IMP_FILES = $(MICROBLAZE_1_BOOTLOOP) $(MICROBLAZE_0_BOOTLOOP)
BRAMINIT_ELF_IMP_FILE_ARGS = -pe microblaze_1 $(MICROBLAZE_1_BOOTLOOP) -pe microblaze_0 $(MICROBLAZE_0_BOOTLOOP)

BRAMINIT_ELF_SIM_FILES = $(MICROBLAZE_1_BOOTLOOP) $(MICROBLAZE_0_BOOTLOOP)
BRAMINIT_ELF_SIM_FILE_ARGS = -pe microblaze_1 $(MICROBLAZE_1_BOOTLOOP) -pe microblaze_0 $(MICROBLAZE_0_BOOTLOOP)

SIM_CMD = xterm -e ./isim_test_mp_sys

BEHAVIORAL_SIM_SCRIPT = simulation/behavioral/$(SYSTEM)_setup.tcl

STRUCTURAL_SIM_SCRIPT = simulation/structural/$(SYSTEM)_setup.tcl

TIMING_SIM_SCRIPT = simulation/timing/$(SYSTEM)_setup.tcl

DEFAULT_SIM_SCRIPT = $(BEHAVIORAL_SIM_SCRIPT)

SIMGEN_OPTIONS = -p $(DEVICE) -lang $(XPS_HDL_LANG) -intstyle $(INTSTYLE) $(SEARCHPATHOPT) $(BRAMINIT_ELF_SIM_FILE_ARGS) -msg __xps/ise/xmsgprops.lst -s isim -tb -external_mem_sim yes


CORE_STATE_DEVELOPMENT_FILES = 

WRAPPER_NGC_FILES = implementation/test_mp_sys_proc_sys_reset_0_wrapper.ngc \
implementation/test_mp_sys_mutex_0_wrapper.ngc \
implementation/test_mp_sys_microblaze_1_ilmb_wrapper.ngc \
implementation/test_mp_sys_microblaze_1_i_bram_ctrl_wrapper.ngc \
implementation/test_mp_sys_microblaze_1_dlmb_wrapper.ngc \
implementation/test_mp_sys_microblaze_1_d_bram_ctrl_wrapper.ngc \
implementation/test_mp_sys_microblaze_1_bram_block_wrapper.ngc \
implementation/test_mp_sys_microblaze_1_wrapper.ngc \
implementation/test_mp_sys_microblaze_0_intc_wrapper.ngc \
implementation/test_mp_sys_microblaze_0_ilmb_wrapper.ngc \
implementation/test_mp_sys_microblaze_0_i_bram_ctrl_wrapper.ngc \
implementation/test_mp_sys_microblaze_0_dlmb_wrapper.ngc \
implementation/test_mp_sys_microblaze_0_d_bram_ctrl_wrapper.ngc \
implementation/test_mp_sys_microblaze_0_bram_block_wrapper.ngc \
implementation/test_mp_sys_microblaze_0_wrapper.ngc \
implementation/test_mp_sys_mailbox_0_wrapper.ngc \
implementation/test_mp_sys_debug_module_wrapper.ngc \
implementation/test_mp_sys_clock_generator_0_wrapper.ngc \
implementation/test_mp_sys_axi_timer_0_wrapper.ngc \
implementation/test_mp_sys_axi4lite_0_wrapper.ngc \
implementation/test_mp_sys_axi4_0_wrapper.ngc \
implementation/test_mp_sys_rs232_0_wrapper.ngc \
implementation/test_mp_sys_mcb_ddr2_wrapper.ngc \
implementation/test_mp_sys_leds_wrapper.ngc \
implementation/test_mp_sys_chipscope_icon_0_wrapper.ngc \
implementation/test_mp_sys_chipscope_ila_0_wrapper.ngc

POSTSYN_NETLIST = implementation/$(SYSTEM).ngc

SYSTEM_BIT = implementation/$(SYSTEM).bit

DOWNLOAD_BIT = implementation/download.bit

SYSTEM_ACE = implementation/$(SYSTEM).ace

UCF_FILE = data/test_mp_sys.ucf

BMM_FILE = implementation/$(SYSTEM).bmm

BITGEN_UT_FILE = etc/bitgen.ut

XFLOW_OPT_FILE = etc/fast_runtime.opt
XFLOW_DEPENDENCY = __xps/xpsxflow.opt $(XFLOW_OPT_FILE)

XPLORER_DEPENDENCY = __xps/xplorer.opt
XPLORER_OPTIONS = -p $(DEVICE) -uc $(SYSTEM).ucf -bm $(SYSTEM).bmm -max_runs 7

FPGA_IMP_DEPENDENCY = $(BMM_FILE) $(POSTSYN_NETLIST) $(UCF_FILE) $(XFLOW_DEPENDENCY)

SDK_EXPORT_DIR = SDK/SDK_Export/hw
SYSTEM_HW_HANDOFF = $(SDK_EXPORT_DIR)/$(SYSTEM).xml
SYSTEM_HW_HANDOFF_BIT = $(SDK_EXPORT_DIR)/$(SYSTEM).bit
SYSTEM_HW_HANDOFF_BMM = $(SDK_EXPORT_DIR)/$(SYSTEM)_bd.bmm
SYSTEM_HW_HANDOFF_DEP = $(SYSTEM_HW_HANDOFF) $(SYSTEM_HW_HANDOFF_BIT) $(SYSTEM_HW_HANDOFF_BMM)
