twrp:
	heimdall flash --BOOT twrp/twrp-3.1.1-0-jfltexx.img --RECOVERY twrp/twrp-3.1.1-0-jfltexx.img

prepare:
	sudo apt-get install bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev android-tools-adb openjdk-8-jdk

#libesd0-dev 

compile:
	bash clone.sh

get:
	wget https://mirrorbits.lineageos.org/full/jfltexx/20180504/lineage-14.1-20180504-nightly-jfltexx-signed.zip
