# program BOOT.bin into spi.
# bootmode 0, spi
# zynq bootimage with [FSBL, sytem_top.bit, lwip app]
# after reboot: ping 192.168.1.10

# to prog use Mars_PM3 hw project and Xilinx Tools -> Program Flash

